version: '3'

services:
    react-frontend:
      build:
        context: .
      environment:
        - NODE_ENV=development
      ports:
        - 8080:3000
      volumes:
        - '.:/app'
        - '/app/node_modules'
